### ISSUE TITLE
This repository is difficult to clone on Windows

### ISSUE THREAD

**Issue by CraftSpider** [wehr-lab/SaundersWehr-Autopilot2019#1]
As title states - if you try to `git clone` this repository, it fails, due to file in the `data/frame_test_2` directory containing colons. Filenames with colons are illegal on Windows, and as such git fails when pulling them.

The workaround is to try cloning, cd into the directory, run `git config core.protectNTFS false`, then try pulling/resetting again. This doesn't pull the files, but makes git ignore them and pull anyways. On the other hand, this does open the user to security issues if this repository were to contain malicious files.

**Comment by sneakers-the-rat** [comment]
does this help, or do i need to rename them in the git history as well? 
https://github.com/auto-pi-lot/autopilot-paper/commit/c1549a8dd8c98725f10931f8c054a8ac8452db5a

**Comment by CraftSpider** [comment]
That fixed the issue, git history can handle it just fine as long as it doesn't actually try to create the files it seems. Thanks for the quick fix!
